

export const LOGIN_PROJECT = 'LOGIN_PROJECT';
export const FIND_CATEGORY = 'FIND_CATEGORY';
export const FIND_LIST_APP_COMPANY = 'FIND_LIST_APP_COMPANY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_DATA_CRAW = 'ADD_DATA_CRAW';
export const CRAW_NAME_WEB = 'CRAW_NAME_WEB';
export const CRAW_LIST_APP_COMPANY = 'CRAW_LIST_APP_COMPANY';
export const CRAW_FIND_LIST_APP_COMPANY = 'CRAW_FIND_LIST_APP_COMPANY';
export const FILL_CATEGORY_ID = 'FILL_CATEGORY_ID';
export const DELETE_APP_COMPANY = 'DELETE_APP_COMPANY';
export const CHECK_DELETE = 'CHECK_DELETE';
export const ON_SEARCH_DATA_COMPANY = 'ON_SEARCH_DATA_COMPANY';
export const ON_LOOK_CATEGORY = 'ON_LOOK_CATEGORY';
export const ON_UPDATE_CATEGORY = 'ON_UPDATE_CATEGORY';
export const ON_DELETE_CATEGORY = 'ON_DELETE_CATEGORY';
export const ON_CHECK_LOADING = 'ON_CHECK_LOADING';
export const ON_REALOAD_CRAW_CATEGORY = 'ON_REALOAD_CRAW_CATEGORY';
export const MESSAGE_CRAW_NAME_WEB = 'MESSAGE_CRAW_NAME_WEB';
export const CHECK_SD_DATABASE = 'CHECK_SD_DATABASE';
export const BEFORE_CRAW_LIST_APP_COMPANY = 'BEFORE_CRAW_LIST_APP_COMPANY';
export const LOADING_FULL_PROJECT = 'LOADING_FULL_PROJECT';
export const LOADING_CATEGORY = 'LOADING_CATEGORY';
export const ON_CHANGE_RESET_DATA = 'ON_CHANGE_RESET_DATA'

